services:
  - type: web
    name: football-analytics-api
    env: python
    plan: free
    region: oregon

    buildCommand: pip install -r backend/requirements.txt

    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHONPATH
        value: .

      - key: CORS_ORIGINS
        value: https://rutejtalati.github.io,http://localhost:5173

      - key: UNDERSTAT_LEAGUE
        value: EPL

      - key: UNDERSTAT_SEASON
        value: "2025"

    healthCheckPath: /api/health
